version: "3.8"
services:
  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}
    ports:
      - 5432:5432
  valkey:
    image: valkey/valkey
    container_name: valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey:/data
volumes:
  postgres_data:
  valkey:

